[package]
name = "physics"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "physics"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
rapier3d = { version = "*", features = [ "simd-stable", "parallel" ] }
