[package]
name = "scene_ops"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "scene_ops"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
nalgebra = "*"
rapier3d-f64 = { version = "*", features = [ "simd-stable", "parallel" ] }