import { type Vector2, Vector3 } from "three";

export const MovementFlag = {
  None: 0,
  Run: 1 << 0,
  Brake: 1 << 1,
  Jump: 1 << 2,
} as const;

export const CorrectionFlag = {
  None: 0,
  Teleport: 1 << 0,
  CollisionPush: 1 << 1,
  StatusOverride: 1 << 2,
  AntiCheatReject: 1 << 3,
} as const;

export const MovementMode = {
  Grounded: "grounded",
  Airborne: "airborne",
  Scripted: "scripted",
  Disabled: "disabled",
} as const;

export type MovementMode = (typeof MovementMode)[keyof typeof MovementMode];

export const AoiPriorityBand = {
  High: "high",
  Medium: "medium",
  Low: "low",
} as const;

export type AoiPriorityBand = (typeof AoiPriorityBand)[keyof typeof AoiPriorityBand];

export interface MoveInputFrame {
  seq: number;
  clientTick: number;
  dtMs: number;
  inputDir: Vector2;
  speedScale: number;
  movementFlags: number;
}

export interface PredictedMoveState {
  seq: number;
  tick: number;
  position: Vector3;
  velocity: Vector3;
  acceleration: Vector3;
  movementMode: MovementMode;
  groundY: number;
}

export interface MovementAck {
  ackSeq: number;
  authTick: number;
  // Movement schema v2: authoritative state timestamp (ms), generated by
  // Scene from the simulation epoch + fixed-tick index. Interpolation uses
  // this as the wall-clock-aligned state timeline.
  serverStateMs: number;
  // Movement schema v2: wall-clock send timestamp (ms) injected at the
  // transport edge. Kept for latency/debug; it is not the state timeline.
  serverSendMs: number;
  position: Vector3;
  velocity: Vector3;
  acceleration: Vector3;
  movementMode: MovementMode;
  // Phase A1-4: server now authoritatively echos ground_z(launch level for
  // current airborne arc)on every ack。required field — wire format always
  // carries it,client predictor's stepAirborne 必须按此值落地。
  groundY: number;
  correctionFlags: number;
  // Audit B-M2 (bevy sweep 2026-04-26): server-authoritative fixed-tick
  // interval (ms) echoed in every ack. Used to detect MovementProfile
  // drift before it accumulates into prediction error.
  serverFixedDtMs: number;
  // Optional latency diagnostics tail. Older 121-byte ACK frames omit these;
  // newer frames append them so the client can split ACK age into Scene/Gate/
  // browser-apply segments without changing movement authority semantics.
  sceneAckMs?: number;
  sceneInputAgeMs?: number;
  sceneQueueLen?: number;
  sceneReplayCount?: number;
  sceneDroppedInputCount?: number;
  sceneMailboxLen?: number;
  sceneTickDriftMs?: number;
  gateSendDelayMs?: number;
}

export interface RemoteMoveSnapshot {
  cid: number;
  serverTick: number;
  // Movement schema v2: authoritative state timestamp (ms), generated by
  // Scene from the simulation epoch + fixed-tick index. Interpolation uses
  // this as the wall-clock-aligned state timeline.
  serverStateMs: number;
  // Movement schema v2: wall-clock send timestamp (ms) injected at the
  // transport edge. Kept for latency/debug; it is not the state timeline.
  serverSendMs: number;
  position: Vector3;
  velocity: Vector3;
  acceleration: Vector3;
  movementMode: MovementMode;
  priorityBand?: AoiPriorityBand;
  priorityScore?: number;
  observerDistance?: number;
  deliveryInterval?: number;
}

export function makeIdleState(position: Vector3): PredictedMoveState {
  return {
    seq: 0,
    tick: 0,
    position: position.clone(),
    velocity: new Vector3(),
    acceleration: new Vector3(),
    movementMode: MovementMode.Grounded,
    groundY: position.y,
  };
}

export function cloneMoveInputFrame(frame: MoveInputFrame): MoveInputFrame {
  return {
    seq: frame.seq,
    clientTick: frame.clientTick,
    dtMs: frame.dtMs,
    inputDir: frame.inputDir.clone(),
    speedScale: frame.speedScale,
    movementFlags: frame.movementFlags,
  };
}

export function clonePredictedMoveState(state: PredictedMoveState): PredictedMoveState {
  return {
    seq: state.seq,
    tick: state.tick,
    position: state.position.clone(),
    velocity: state.velocity.clone(),
    acceleration: state.acceleration.clone(),
    movementMode: state.movementMode,
    groundY: state.groundY,
  };
}

export function cloneMovementAck(ack: MovementAck): MovementAck {
  const cloned: MovementAck = {
    ackSeq: ack.ackSeq,
    authTick: ack.authTick,
    serverStateMs: ack.serverStateMs,
    serverSendMs: ack.serverSendMs,
    position: ack.position.clone(),
    velocity: ack.velocity.clone(),
    acceleration: ack.acceleration.clone(),
    movementMode: ack.movementMode,
    correctionFlags: ack.correctionFlags,
    serverFixedDtMs: ack.serverFixedDtMs,
    groundY: ack.groundY,
  };
  if (ack.sceneAckMs !== undefined) cloned.sceneAckMs = ack.sceneAckMs;
  if (ack.sceneInputAgeMs !== undefined) cloned.sceneInputAgeMs = ack.sceneInputAgeMs;
  if (ack.sceneQueueLen !== undefined) cloned.sceneQueueLen = ack.sceneQueueLen;
  if (ack.sceneReplayCount !== undefined) cloned.sceneReplayCount = ack.sceneReplayCount;
  if (ack.sceneDroppedInputCount !== undefined) {
    cloned.sceneDroppedInputCount = ack.sceneDroppedInputCount;
  }
  if (ack.sceneMailboxLen !== undefined) cloned.sceneMailboxLen = ack.sceneMailboxLen;
  if (ack.sceneTickDriftMs !== undefined) cloned.sceneTickDriftMs = ack.sceneTickDriftMs;
  if (ack.gateSendDelayMs !== undefined) cloned.gateSendDelayMs = ack.gateSendDelayMs;
  return cloned;
}

export function cloneRemoteMoveSnapshot(snapshot: RemoteMoveSnapshot): RemoteMoveSnapshot {
  const cloned: RemoteMoveSnapshot = {
    cid: snapshot.cid,
    serverTick: snapshot.serverTick,
    serverStateMs: snapshot.serverStateMs,
    serverSendMs: snapshot.serverSendMs,
    position: snapshot.position.clone(),
    velocity: snapshot.velocity.clone(),
    acceleration: snapshot.acceleration.clone(),
    movementMode: snapshot.movementMode,
  };
  if (snapshot.priorityBand !== undefined) cloned.priorityBand = snapshot.priorityBand;
  if (snapshot.priorityScore !== undefined) cloned.priorityScore = snapshot.priorityScore;
  if (snapshot.observerDistance !== undefined) cloned.observerDistance = snapshot.observerDistance;
  if (snapshot.deliveryInterval !== undefined) cloned.deliveryInterval = snapshot.deliveryInterval;
  return cloned;
}
