[package]
name = "sceneserver_nif_sceneops"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "sceneserver_nif_sceneops"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
